flaskapp:
  build: .
  links:
    - mysql:mysql
    - redis:redis
  volumes:
    - .:/usr/src
  environment:
    - APP_SECRET=mydevsecret
  expose:
    - "3031"
  command: uwsgi --ini /usr/src/app.ini
nginx:
  image: nginx:latest
  links:
    - flaskapp:uwsgi
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./static:/usr/src/static
mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=emarroot
  ports:
   - "3306:3306"
redis:
  image: redis:latest
  ports:
    - "6379:6379"